//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDAL.EntityModel
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MerchantEntities : DbContext
    {
        public MerchantEntities()
        : base("metadata=res://*/EntityModel.MerchantEntityModel.csdl|res://*/EntityModel.MerchantEntityModel.ssdl|res://*/EntityModel.MerchantEntityModel.msl;provider=System.Data.SqlClient;provider connection string=\"data source=(LocalDB)\\MSSQLLocalDB;attachdbfilename=|DataDirectory|\\Merchant.mdf;integrated security=True;connect timeout=30;MultipleActiveResultSets=True;App=EntityFramework\"")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommonData> CommonDatas { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
    }
}
